---
title: "Homework Quiz"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br><br>

1. I want to predict how well 6 year-olds are going to do in their final school exams. Using the following variables am I likely under-fitting, fitting well or over-fitting? Postcode, gender, reading level, score in maths test, date of birth, family income.

Over-fitting, as there are lot's of extraneous variables such as postcode or score in maths test, which may be correlated with family income and reading level, respectively.

2. If I have two models, one with an AIC score of 34,902 and the other with an AIC score of 33,559 which model should I use?

The lower AIC score of 33,559 is better.

3. I have two models, the first with: r-squared: 0.44, adjusted r-squared: 0.43. The second with: r-squared: 0.47, adjusted r-squared: 0.41. Which one should I use?

We should use the first, as although the r-squared is lower, the adjusted r-squared is higher and does not vary a lot from the r-squared like in the second (which indicates overfitting).

4. I have a model with the following errors: RMSE error on test set: 10.3, RMSE error on training data: 10.4. Do you think this model is over-fitting?


5. How does k-fold validation work?


6. What is a validation set? When do you need one?


7. Describe how backwards selection works.


8. Describe how best subset selection works.





